module.exports = {
    products: [
        {
            _id:'111111111111111111111111',
            name: 'Linea Classic',
            category: 'Eleccion Mujeres',
            image:'./img/IMG_2414.JPG',
            img_1:'img/IMG_2921.JPG',
            img_2:'img/IMG_2903.JPG',
            img_3:'img/IMG_2919.JPG',
            img_4:'img/IMG_2905.JPG',
            img_5:'img/IMG_2911.JPG',
            img_6:'img/IMG_2917.JPG',
            price: 103500,
            rating: 4.5,
            nomReviewa: 10,
            countInStock: 12,
            info: 'Una línea que sigue un modelo de tendencia de moda americano, con bolsillos amplios y corte muy a la moda.',
            tallac: [],
            tallap: [],
            color: []

        },
        {
            _id:'222222222222222222222222',
            name: 'Linea Functional',
            category: 'Eleccion Mujeres',
            image:'./img/IMG_2424.png',
            img_1:'img/IMG_2898.JPG',
            img_2:'img/IMG_2886.JPG',
            img_3:'img/IMG_2884.JPG',
            img_4:'img/IMG_2877.png',
            img_5:'img/IMG_2872.png',
            img_6:'img/IMG_2874.png',
            price: 117000,
            rating: 4.0,
            nomReviewa: 15,
            countInStock: 12,
            info: 'Una línea con más accesorios pensado en la funcionalidad en diferentes entornos, esta línea maneja una mezcla de tendencias de modas que la resultan muy efectiva en todos los ambientes.',
            tallac: [],
            tallap: [],
            color: []
        },
        {
            _id:'333333333333333333333333',
            name: 'Linea Confort',
            category: 'Eleccion Mujeres',
            image:'./img/IMG_2399.png',
            img_1:'img/CONFORTM1.jpeg',
            img_2:'img/CONFORTM2.jpeg',
            img_3:'img/CONFORTM3.jpeg',
            img_4:'img/CONFORTM4.jpeg',
            img_5:'img/CONFORTM5.jpeg',
            img_6:'img/CONFORTM6.jpeg',
            price: 90000,
            rating: 4.0,
            nomReviewa: 15,
            countInStock: 12,
            info: 'Una línea muy a la moda con un toque juvenil, sport y resaltando entre sus características la comodidad. Sigue modelos de tendencias actuales y confortables.',
            tallac: [],
            tallap: [],
            color: []       
        },
        {
            _id:'444444444444444444444444',
            name: 'Linea Classic',
            category: 'Eleccion Hombres',
            image:'./img/IMG_2421.png',
            img_1:'img/IMG_2982.JPG',
            img_2:'img/IMG_2990.JPG',
            img_3:'img/IMG_2995.JPG',
            img_4:'img/IMG_2986.png',
            img_5:'img/IMG_2993.png',
            img_6:'img/IMG_3002.png',
            price: 103500,
            rating: 4.5,
            nomReviewa: 10,
            countInStock: 12,
            info: 'Una línea que sigue un modelo de tendencia de moda americano, con bolsillos amplios y corte muy a la moda.',
            tallac: [],
            tallap: [],
            color: []
        },
        {
            _id:'555555555555555555555555',
            name: 'Linea Functional',
            category: 'Eleccion Hombres',
            image:'./img/IMG_2411.png',
            img_1:'img/IMG_2976.JPG',
            img_2:'img/IMG_2969.JPG',
            img_3:'img/IMG_2964.JPG',
            img_4:'img/IMG_2948.png',
            img_5:'img/IMG_2956.png',
            img_6:'img/IMG_2960.png',
            price: 117000,
            rating: 4.0,
            nomReviewa: 15,
            countInStock: 12,
            info: 'Una línea con más accesorios pensado en la funcionalidad en diferentes entornos, esta línea maneja una mezcla de tendencias de modas que la resultan muy efectiva en todos los ambientes.',
            tallac: [],
            tallap: [],
            color: []
        },
        {
            _id:'666666666666666666666666',
            name: 'Linea Confort',
            category: 'Eleccion Hombres',
            image:'./img/IMG_2385.JPG',
            img_1:'img/IMG_2403.png',
            img_2:'img/CONFORTH1.jpeg',
            img_3:'img/CONFORTH2.jpeg',
            img_4:'img/CONFORTH3.jpeg',
            img_5:'img/CONFORTH4.jpeg',
            img_6:'img/CONFORTH5.jpeg',
            price: 90000,
            rating: 4.0,
            nomReviewa: 15,
            countInStock: 12,
            info: 'Una línea muy a la moda con un toque juvenil, sport y resaltando entre sus características la comodidad. Sigue modelos de tendencias actuales y confortables.',
            tallac: [],
            tallap: [],
            color: []
        },
    ],
};